<template>
  <div class="ma-content-block lg:flex justify-between p-4">
    <!-- CRUD 组件 -->
    <ma-crud :options="crud" :columns="columns" ref="crudRef">
    </ma-crud>
  </div>
</template>

<script setup>
  import { ref, reactive, computed } from 'vue'
  import api from '@/api/summaryOrder'
  import { Message } from '@arco-design/web-vue'

  const crudRef = ref()


  const crud = reactive({
    api: api.getPageList,
    recycleApi: api.getRecyclePageList,
    showIndex: false,
    searchColNumber: 3,
    pageLayout: 'fixed',
    rowSelection: { showCheckedAll: true },
    operationColumn: true,
    operationColumnWidth: 160,
    add: { show: true, api: api.save, auth: ['/summaryOrder/save'] },
    edit: { show: true, api: api.update, auth: ['/summaryOrder/update'] },
    delete: { show: true, api: api.delete, auth: ['/summaryOrder/destroy'] },
    recovery: { show: true, api: api.recovery, auth: ['/summaryOrder/recovery']},
    formOption: { width: 800 },
  })

  const columns = reactive([
    {
      title: '主键',
      dataIndex: 'id',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: true, message: '主键必填' }],
    },
    {
      title: '汇总人',
      dataIndex: 'summary_sys_id',
      width: 100,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      
      formType: 'select',
      commonRules: [{ required: false, message: '汇总人必填' }],
    },
    {
      title: '审图人',
      dataIndex: 'confirm_sys_id',
      width: 100,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      
      formType: 'select',
      commonRules: [{ required: false, message: '审图人必填' }],
    },
    {
      title: '受理人',
      dataIndex: 'assign_sys_id',
      width: 100,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      
      formType: 'select',
      commonRules: [{ required: false, message: '受理人必填' }],
    },
    {
      title: '汇总批次ID',
      dataIndex: 'summary_batch_id',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '汇总批次ID必填' }],
    },
    {
      title: '汇总批次号',
      dataIndex: 'summary_batch_code',
      width: 180,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '汇总批次号必填' }],
    },
    {
      title: '文件名',
      dataIndex: 'file',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'upload',
      type: 'file',
      returnType: 'url',
      multiple: false,
      commonRules: [{ required: false, message: '文件名必填' }],
    },
    {
      title: '修正文件名',
      dataIndex: 'file_correct',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'upload',
      type: 'file',
      returnType: 'url',
      multiple: false,
      commonRules: [{ required: false, message: '修正文件名必填' }],
    },
    {
      title: '识别符',
      dataIndex: 'identify',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '识别符必填' }],
    },
    {
      title: '产品名称',
      dataIndex: 'product_name',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '产品名称必填' }],
    },
    {
      title: '产品类别',
      dataIndex: 'type_id',
      width: 100,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      
      formType: 'select',
      commonRules: [{ required: false, message: '产品类别必填' }],
    },
    {
      title: '产品级别',
      dataIndex: 'grade_id',
      width: 100,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      
      formType: 'select',
      commonRules: [{ required: false, message: '产品级别必填' }],
    },
    {
      title: '画面类型',
      dataIndex: 'picture_type_id',
      width: 100,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      
      formType: 'select',
      commonRules: [{ required: false, message: '画面类型必填' }],
    },
    {
      title: '宽度',
      dataIndex: 'width',
      width: 180,
      search: false,
      addDisplay: true, addDefaultValue: 0.00,
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '宽度必填' }],
    },
    {
      title: '高度',
      dataIndex: 'height',
      width: 180,
      search: false,
      addDisplay: true, addDefaultValue: 0.00,
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '高度必填' }],
    },
    {
      title: '备注',
      dataIndex: 'remark',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '备注必填' }],
    },
    {
      title: '汇总数量',
      dataIndex: 'nums',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '汇总数量必填' }],
    },
    {
      title: '加急数量',
      dataIndex: 'urgent_nums',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '加急数量必填' }],
    },
    {
      title: '完稿预览图',
      dataIndex: 'finish_preview',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '完稿预览图必填' }],
    },
    {
      title: '美工文件',
      dataIndex: 'pre_file',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'upload',
      type: 'file',
      returnType: 'url',
      multiple: false,
      commonRules: [{ required: false, message: '美工文件必填' }],
    },
    {
      title: '打印文件',
      dataIndex: 'print_file',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'upload',
      type: 'file',
      returnType: 'url',
      multiple: false,
      commonRules: [{ required: false, message: '打印文件必填' }],
    },
    {
      title: '工艺文件',
      dataIndex: 'craft_file',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'upload',
      type: 'file',
      returnType: 'url',
      multiple: false,
      commonRules: [{ required: false, message: '工艺文件必填' }],
    },
    {
      title: '审图反馈信息',
      dataIndex: 'confirm_feedback',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '审图反馈信息必填' }],
    },
    {
      title: '喷印状态',
      dataIndex: 'print_status',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '喷印状态必填' }],
    },
    {
      title: '当班印量',
      dataIndex: 'duty_nums',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '当班印量必填' }],
    },
    {
      title: '创建者',
      dataIndex: 'created_by',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '创建者必填' }],
    },
    {
      title: '更新者',
      dataIndex: 'updated_by',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '更新者必填' }],
    },
    {
      title: '创建时间',
      dataIndex: 'create_time',
      width: 180,
      search: true,
      addDisplay: false, 
      editDisplay: false,
      hide: false,
      searchFormType: 'range',
      showTime: true,
      formType: 'date',
      commonRules: [{ required: false, message: '创建时间必填' }],
    },
    {
      title: '修改时间',
      dataIndex: 'update_time',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      searchFormType: 'range',
      showTime: true,
      formType: 'date',
      commonRules: [{ required: false, message: '修改时间必填' }],
    },
  ])
</script>
