<template>
  <div class="justify-between p-4 ma-content-block lg:flex">
    <!-- CRUD 组件 -->
    <ma-crud :options="crud" :columns="columns" ref="crudRef">
    </ma-crud>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted, watch } from 'vue'
import api from '@/api/clientGroup'
import { Message } from '@arco-design/web-vue'
import { useSysInfoStore } from '@/store'

const crudRef = ref()
const sysInfoStore = useSysInfoStore()

const crud = reactive({
  api: api.getPageList,
  recycleApi: api.getRecyclePageList,
  showIndex: false,
  searchColNumber: 3,
  pageLayout: 'fixed',
  rowSelection: { showCheckedAll: true },
  operationColumn: sysInfoStore.info.is_admin ? true : false,
  operationColumnWidth: 160,
  add: {
    show: sysInfoStore.info.is_admin ? true : false,
    api: api.save,
    // auth: ['/clientGroup/save']
  },
  edit: {
    show: sysInfoStore.info.is_admin ? true : false,
    api: api.update,
    // auth: ['/clientGroup/update']
  },
  delete: {
    show: sysInfoStore.info.is_admin ? true : false,
    api: api.delete,
    // auth: ['/clientGroup/destroy']
  },
  recovery: {
    show: sysInfoStore.info.is_admin ? true : false,
    api: api.recovery,
    // auth: ['/clientGroup/recovery']
  },
  formOption: { width: 800 },
})

const columns = reactive([
  {
    title: '主键',
    dataIndex: 'id',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: true, message: '主键必填' }],
  },
  {
    title: '人员ID',
    dataIndex: 'sys_user_id',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: false, message: '人员ID必填' }],
  },
  {
    title: '公司名称',
    dataIndex: 'company_name',
    width: 180,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    rules: [{ required: true, message: '公司名称必填' }],
  },
  {
    title: '办公地点',
    dataIndex: 'address',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    rules: [{ required: true, message: '办公地点必填' }],
  },
  {
    title: '品牌名称',
    dataIndex: 'brand_name',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '品牌名称必填' }],
  },
  {
    title: '行业类别',
    dataIndex: 'profession_type_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/clientProfessionType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    // commonRules: [{ required: false, message: '行业类别必填' }],
  },
  {
    title: '联系人',
    dataIndex: 'contact',
    width: 180,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    rules: [{ required: true, message: '联系人必填' }],
  },
  {
    title: '手机号',
    dataIndex: 'mobile',
    width: 180,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    rules: [{ required: true, message: '手机号必填' }],
  },
  {
    title: '微信号',
    dataIndex: 'wechat',
    width: 180,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '微信号必填' }],
  },
  {
    title: '发票抬头',
    dataIndex: 'fapiao_title',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '发票抬头必填' }],
  },
  {
    title: '税号',
    dataIndex: 'company_code',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '税号必填' }],
  },

  // 权限说明
  {
    title: '客户级别',
    dataIndex: 'level_type_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/clientLevelType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    // commonRules: [{ required: false, message: '客户级别必填' }],
  },
  {
    title: '纳税人性质',
    dataIndex: 'taxpayer_type_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/clientTaxpayerType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    // commonRules: [{ required: false, message: '纳税人性质必填' }],
  },
  {
    title: '结账方式',
    dataIndex: 'settle_method',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { name: 'bizSettleMethod', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'select',
    // commonRules: [{ required: false, message: '结账方式必填' }],
  },
  {
    title: '信用级别',
    dataIndex: 'credit_type_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/clientCreditType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    // commonRules: [{ required: false, message: '信用级别必填' }],
  },
  {
    title: '授信额度',
    dataIndex: 'credit_amount_total',
    width: 180,
    search: false,
    addDisplay: true,
    addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '授信额度必填' }],
  },
  {
    title: '已用额度',
    dataIndex: 'credit_amount_usage',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: false, message: '已用额度必填' }],
  },
  {
    title: '剩余额度',
    dataIndex: 'credit_amount',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: false, message: '已用额度必填' }],
  },
  {
    title: '物流费用方式',
    dataIndex: 'logistics_type_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/clientLogisticsType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    // commonRules: [{ required: true, message: '物流费用方式必填' }],
  },
  {
    title: '月结起点',
    dataIndex: 'montly_checkout_start',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '月结起点必填' }],
  },
  {
    title: '月结支付日',
    dataIndex: 'monthly_checkout_date',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '月结支付日必填' }],
  },
  {
    title: '云盘剩余量G',
    dataIndex: 'cloud_disk_amount',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '云盘容量必填' }],
  },
  {
    title: '云盘总量G',
    dataIndex: 'cloud_disk_total',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    // addDefaultValue: 5,
    // defaultValue: 5,
    formType: 'select',
    dict: {
      data: [
        {
          label: '5',
          value: 5,
        },
        {
          label: '10',
          value: 10,
        },
        {
          label: '20',
          value: 20,
        },
        {
          label: '100',
          value: 100,
        },
        {
          label: '200',
          value: 200,
        },
      ],
    },
    // commonRules: [{ required: true, message: '云盘容量必填' }],
  },
  {
    title: '营业执照照片',
    dataIndex: 'business_license',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'upload',
    type: 'image',
    returnType: 'url',
    // commonRules: [{ required: true, message: '营业执照照片必填' }],
  },
  // {
  //   title: '品牌权属',
  //   dataIndex: 'brand_right',
  //   width: 100,
  //   search: false,
  //   addDisplay: true,
  //   editDisplay: true,
  //   hide: false,
  //   dict: { url: '/clientBrandRight/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
  //   formType: 'select',
  //   // commonRules: [{ required: false, message: '品牌权属必填' }],
  // },
  // {
  //   title: '经营类型',
  //   dataIndex: 'business_type_id',
  //   width: 100,
  //   search: false,
  //   addDisplay: true,
  //   editDisplay: true,
  //   hide: false,
  //   dict: { url: '/clientBusinessType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
  //   formType: 'select',
  //   // commonRules: [{ required: false, message: '经营类型必填' }],
  // },
  // {
  //   title: '销售类型',
  //   dataIndex: 'sales_type_id',
  //   width: 100,
  //   search: false,
  //   addDisplay: true,
  //   editDisplay: true,
  //   hide: false,
  //   dict: { url: '/clientSalesType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
  //   formType: 'select',
  //   commonRules: [{ required: true, message: '销售类型必填' }],
  // },
  {
    title: '推荐人手机号',
    dataIndex: 'recommend_mobile',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: false, message: '推荐人手机号码必填' }],
  },
  {
    title: '连锁模式权',
    dataIndex: 'chain_mode',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { name: 'data_status', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'radio',
    // commonRules: [{ required: false, message: '连锁模式权限必填' }],
  },
  {
    title: '小程序相册权',
    dataIndex: 'miniapp_usage',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { name: 'data_status', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'radio',
    // commonRules: [{ required: false, message: '小程序相册权限必填' }],
  },
  {
    title: '下单可用状态',
    dataIndex: 'order_usage',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { name: 'data_status', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'radio',
    // commonRules: [{ required: false, message: '下单状态必填' }],
  },
  {
    title: '账户可用状态',
    dataIndex: 'status',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { name: 'data_status', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'radio',
    // commonRules: [{ required: false, message: '账户状态必填' }],
  },
  {
    title: '创建者',
    dataIndex: 'created_by',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: false, message: '创建者必填' }],
  },
  {
    title: '更新者',
    dataIndex: 'updated_by',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: false, message: '更新者必填' }],
  },
  {
    title: '创建时间',
    dataIndex: 'create_time',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    searchFormType: 'range',
    showTime: true,
    formType: 'date',
    commonRules: [{ required: false, message: '创建时间必填' }],
  },
  {
    title: '修改时间',
    dataIndex: 'update_time',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    searchFormType: 'range',
    showTime: true,
    formType: 'date',
    commonRules: [{ required: false, message: '修改时间必填' }],
  },
])
</script>
