<template>
  <div class="justify-between p-4 ma-content-block lg:flex">
    <!-- CRUD 组件 -->
    <ma-crud :options="crud" :columns="columns" ref="crudRef">
    </ma-crud>
  </div>
</template>

<script setup>
import { ref, reactive, computed } from 'vue'
import api from '@/api/product'
import { Message } from '@arco-design/web-vue'

const crudRef = ref()


const crud = reactive({
  api: api.getPageList,
  recycleApi: api.getRecyclePageList,
  showIndex: false,
  searchColNumber: 3,
  pageLayout: 'fixed',
  rowSelection: { showCheckedAll: true },
  operationColumn: true,
  operationColumnWidth: 160,
  add: { show: true, api: api.save, auth: ['/product/save'] },
  edit: { show: true, api: api.update, auth: ['/product/update'] },
  delete: { show: true, api: api.delete, auth: ['/product/destroy'] },
  recovery: { show: true, api: api.recovery, auth: ['/product/recovery'] },
  formOption: { width: 800 },
})

const columns = reactive([
  {
    title: '主键',
    dataIndex: 'id',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: true, message: '主键必填' }],
  },
  {
    title: '名称',
    dataIndex: 'name',
    width: 180,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    commonRules: [{ required: true, message: '名称必填' }],
  },
  {
    title: '拼音',
    dataIndex: 'pinyin',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: true,
    formType: 'input',
    // commonRules: [{ required: true, message: '名称必填' }],
  },
  // {
  //   title: '计价类型',
  //   dataIndex: 'pricing_type',
  //   width: 100,
  //   search: true,
  //   addDisplay: true,
  //   editDisplay: true,
  //   hide: false,
  //   dict: { name: 'bizPricingType', props: { label: 'label', value: 'value' }, translation: true },
  //   formType: 'select',
  //   commonRules: [{ required: true, message: '计价类型必填' }],
  // },
  {
    title: '产品类别',
    dataIndex: 'type_id',
    width: 100,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/productType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    commonRules: [{ required: true, message: '产品类别必填' }],
  },
  {
    title: '产品级别',
    dataIndex: 'grade_id',
    width: 100,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/productGrade/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    commonRules: [{ required: true, message: '产品级别必填' }],
  },
  {
    title: '画面类型',
    dataIndex: 'picture_type_id',
    width: 100,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/productPictureType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    commonRules: [{ required: true, message: '画面类型必填' }],
  },
  {
    title: '工艺组',
    dataIndex: 'craft_grp_ids',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'select',
    multiple: true,
    dict: { url: '/craftGroup/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    // commonRules: [{ required: false, message: '必填' }],
    editDefaultValue: async (record) => {
      const response = await api.read(record.id)
      return response.data.craft_list.map((item) => item.id)
    },
  },
  {
    title: '宽度最小',
    dataIndex: 'width_min',
    width: 180,
    search: false,
    addDisplay: true, addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'input',
    commonRules: [{ required: false, message: '宽度最小必填' }],
  },
  {
    title: '宽度最大',
    dataIndex: 'width_max',
    width: 180,
    search: false,
    addDisplay: true, 
    addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'input',
    extra: '若设置宽度进模板，按该设定值',
    commonRules: [{ required: false, message: '宽度最大必填' }],
  },
  {
    title: '高度最小',
    dataIndex: 'height_min',
    width: 180,
    search: false,
    addDisplay: true, addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'input',
    commonRules: [{ required: false, message: '高度最小必填' }],
  },
  {
    title: '高度最大',
    dataIndex: 'height_max',
    width: 180,
    search: false,
    addDisplay: true, addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'input',
    extra: '若设置高度进模板，按该设定值',
    commonRules: [{ required: false, message: '高度最大必填' }],
  },
  {
    title: '宽度进模板',
    dataIndex: 'is_width_default',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { name: 'data_status', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'radio',
    commonRules: [{ required: false, message: '宽度进入标准模板必填' }],
  },
  {
    title: '高度进模板',
    dataIndex: 'is_height_default',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { name: 'data_status', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'radio',
    commonRules: [{ required: false, message: '高度进入标准模板必填' }],
  },
  {
    title: '计价方式',
    dataIndex: 'pricing_type_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/pricingType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    commonRules: [{ required: true, message: '计价方式必填' }],
  },
  {
    title: '计量单位',
    dataIndex: 'pricing_unit_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/pricingUnit/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    commonRules: [{ required: true, message: '计量单位必填' }],
  },
  {
    title: '标准价',
    dataIndex: 'price',
    width: 180,
    search: false,
    addDisplay: false,
    addDefaultValue: 0.00,
    editDisplay: false,
    hide: true,
    formType: 'input',
    // commonRules: [{ required: false, message: '宽度最小必填' }],
  },
  {
    title: '最低限价',
    dataIndex: 'price_min',
    width: 180,
    search: false,
    addDisplay: true,
    addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'input',
    commonRules: [{ required: false, message: '最低限价必填' }],
  },
  {
    title: '最高限价',
    dataIndex: 'price_max',
    width: 180,
    search: false,
    addDisplay: true,
    addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'input',
    commonRules: [{ required: false, message: '最高限价必填' }],
  },
  // {
  //   title: '自动推送',
  //   dataIndex: 'is_auto_push',
  //   width: 100,
  //   search: true,
  //   addDisplay: true,
  //   editDisplay: true,
  //   hide: false,
  //   addDefaultValue: 1,
  //   dict: { name: 'data_status', props: { label: 'label', value: 'value' }, translation: true },
  //   formType: 'radio',
  //   commonRules: [{ required: true, message: '启用状态必填' }],
  // },
  {
    title: '启用状态',
    dataIndex: 'enabled',
    width: 100,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    addDefaultValue: 1,
    dict: { name: 'data_status', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'radio',
    commonRules: [{ required: true, message: '启用状态必填' }],
  },
  // {
  //   title: '详情页',
  //   dataIndex: 'desc_json',
  //   width: 180,
  //   search: false,
  //   addDisplay: true,
  //   editDisplay: true,
  //   hide: false,
  //   formType: 'editor',
  //   commonRules: [{ required: false, message: '详情页必填' }],
  //   hide: true,
  // },
  {
    title: '详情图',
    dataIndex: 'desc_json',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'upload',
    type: 'image',
    returnType: 'url',
    multiple: false,
    commonRules: [{ required: false, message: '详情图必填' }],
  },
  {
    title: '创建者',
    dataIndex: 'created_by',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: false, message: '创建者必填' }],
  },
  {
    title: '更新者',
    dataIndex: 'updated_by',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: false, message: '更新者必填' }],
  },
  {
    title: '创建时间',
    dataIndex: 'create_time',
    width: 180,
    search: true,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    searchFormType: 'range',
    showTime: true,
    formType: 'date',
    commonRules: [{ required: false, message: '创建时间必填' }],
  },
  {
    title: '修改时间',
    dataIndex: 'update_time',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    searchFormType: 'range',
    showTime: true,
    formType: 'date',
    commonRules: [{ required: false, message: '修改时间必填' }],
  },
])
</script>
