<template>
  <div class="justify-between p-4 ma-content-block lg:flex">
    <!-- CRUD 组件 -->
    <ma-crud :options="crud" :columns="columns" ref="crudRef">
      <!-- 操作前置扩展 -->
      <template #operationBeforeExtend="{ record }">
        <a-button status="success" v-if="record.status === 1" @click="openModal(record)" v-auth="[]">
          <icon-check /> {{ '通过' }}
        </a-button>
        <a-button status="danger" v-if="record.status === 1" @click="rejectApply(record)" v-auth="[]">
          <icon-close /> {{ '拒绝' }}
        </a-button>
      </template>
    </ma-crud>
    <div>
      <ma-form-modal ref="modalRef" v-model:visible="visible" :hide-title="true" :width="800" :column="applyColumn"
        :submit="applySubmit">
      </ma-form-modal>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, computed } from 'vue'
import api from '@/api/clientApply'
import { Message, Modal } from '@arco-design/web-vue'
import MaFormModal from "@/components/ma-form-modal/index.vue"

const crudRef = ref()
const modalRef = ref()
const visible = ref(false)

const openModal = (record) => {
  Object.keys(record).forEach((key) => {
    modalRef.value.form[key] = record[key]
  })
  visible.value = true
}

const rejectApply = async (record) => {
  Modal.info({
    title: '提示',
    content: '确定吗？',
    simple: false,
    okText: '确定',
    cancelText: '取消',
    onOk: () => {
      api.rejectApply({
        id: record.id,
      }).then(res => {
        if (res.code == 200) {
          Message.success('操作成功')
          console.log(crudRef)
          crudRef.value.refresh()
        } else {
          Message.error('操作失败')
        }
      })
    },
  })
  return
}

const applySubmit = (formData) => {
  console.log(formData)
  api.passApply(formData)
    .then(res => {
      console.log('res', res)
      if (res.code == 200) {
        Message.success('审核成功')
        crudRef.value.refresh()
      } else {
        Message.error('审核失败')
      }
    })
  return true
}

const applyColumn = reactive([
  {
    title: '公司名称',
    dataIndex: 'company_name',
    width: 180,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    rules: [{ required: true, message: '公司名称必填' }],
  },
  {
    title: '办公地点',
    dataIndex: 'address',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    rules: [{ required: true, message: '办公地点必填' }],
  },
  {
    title: '品牌名称',
    dataIndex: 'brand_name',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '品牌名称必填' }],
  },
  {
    title: '行业类别',
    dataIndex: 'profession_type_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/clientProfessionType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    // commonRules: [{ required: false, message: '行业类别必填' }],
  },
  {
    title: '联系人',
    dataIndex: 'contact',
    width: 180,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    rules: [{ required: true, message: '联系人必填' }],
  },
  {
    title: '手机号',
    dataIndex: 'mobile',
    width: 180,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    rules: [{ required: true, message: '手机号必填' }],
  },
  {
    title: '微信号',
    dataIndex: 'wechat',
    width: 180,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '微信号必填' }],
  },
  {
    title: '发票抬头',
    dataIndex: 'fapiao_title',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '发票抬头必填' }],
  },
  {
    title: '税号',
    dataIndex: 'company_code',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '税号必填' }],
  },

  // 权限说明
  {
    title: '客户级别',
    dataIndex: 'level_type_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/clientLevelType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    // commonRules: [{ required: false, message: '客户级别必填' }],
  },
  {
    title: '纳税人性质',
    dataIndex: 'taxpayer_type_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/clientTaxpayerType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    // commonRules: [{ required: false, message: '纳税人性质必填' }],
  },
  {
    title: '结账方式',
    dataIndex: 'settle_method',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { name: 'bizSettleMethod', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'select',
    rules: [{ required: true, message: '结账方式必填' }],
  },
  {
    title: '信用级别',
    dataIndex: 'credit_type_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/clientCreditType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    // commonRules: [{ required: false, message: '信用级别必填' }],
  },
  {
    title: '授信额度',
    dataIndex: 'credit_amount_total',
    width: 180,
    search: false,
    addDisplay: true, addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '授信额度必填' }],
  },
  {
    title: '已用额度',
    dataIndex: 'credit_amount',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: false, message: '已用额度必填' }],
  },
  {
    title: '物流费用方式',
    dataIndex: 'logistics_type_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/clientLogisticsType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    // commonRules: [{ required: true, message: '物流费用方式必填' }],
  },
  {
    title: '月结起点',
    dataIndex: 'montly_checkout_start',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '月结起点必填' }],
  },
  {
    title: '月结支付日',
    dataIndex: 'monthly_checkout_date',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '月结支付日必填' }],
  },
  {
    title: '云盘容量(G)',
    dataIndex: 'cloud_disk_amount',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    // addDefaultValue: 5,
    // defaultValue: 5,
    formType: 'select',
    dict: {
      data: [
        {
          label: '5',
          value: 5,
        },
        {
          label: '10',
          value: 10,
        },
        {
          label: '20',
          value: 20,
        },
        {
          label: '100',
          value: 100,
        },
        {
          label: '200',
          value: 200,
        },
      ],
    },
    // commonRules: [{ required: true, message: '云盘容量必填' }],
  },
  {
    title: '营业执照照片',
    dataIndex: 'business_license',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'upload',
    type: 'image',
    returnType: 'url',
    // commonRules: [{ required: true, message: '营业执照照片必填' }],
  },
  // {
  //   title: '品牌权属',
  //   dataIndex: 'brand_right',
  //   width: 100,
  //   search: false,
  //   addDisplay: true,
  //   editDisplay: true,
  //   hide: false,
  //   dict: { url: '/clientBrandRight/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
  //   formType: 'select',
  //   // commonRules: [{ required: false, message: '品牌权属必填' }],
  // },
  // {
  //   title: '经营类型',
  //   dataIndex: 'business_type_id',
  //   width: 100,
  //   search: false,
  //   addDisplay: true,
  //   editDisplay: true,
  //   hide: false,
  //   dict: { url: '/clientBusinessType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
  //   formType: 'select',
  //   // commonRules: [{ required: false, message: '经营类型必填' }],
  // },
  // {
  //   title: '销售类型',
  //   dataIndex: 'sales_type_id',
  //   width: 100,
  //   search: false,
  //   addDisplay: true,
  //   editDisplay: true,
  //   hide: false,
  //   dict: { url: '/clientSalesType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
  //   formType: 'select',
  //   commonRules: [{ required: true, message: '销售类型必填' }],
  // },
  {
    title: '推荐人手机号',
    dataIndex: 'recommend_mobile',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: false, message: '推荐人手机号码必填' }],
  },
  {
    title: '系统主帐号',
    dataIndex: 'username',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    rules: [{ required: true, message: '系统主帐号必填' }],
  },
  {
    title: '系统初始密码',
    dataIndex: 'password',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    rules: [{ required: true, message: '初始密码必填' }],
  },
  // {
  //   title: '品牌证书',
  //   dataIndex: 'brand_certificate',
  //   width: 180,
  //   search: false,
  //   addDisplay: true,
  //   editDisplay: true,
  //   hide: false,
  //   formType: 'upload',
  //   type: 'image',
  //   returnType: 'url',
  //   // commonRules: [{ required: true, message: '品牌证书必填' }],
  // },
  {
    title: '营销团队',
    dataIndex: 'market_dept_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: {
      url: '/core/dept/index?role_code=marketing',
      props: { label: 'name', value: 'id' },
      translation: true
    },
    formType: 'select',
    rules: [{ required: true, message: '营销团队必填' }],
  },
  {
    title: '客服团队',
    dataIndex: 'cs_dept_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: {
      url: '/core/dept/index?role_code=customerService',
      props: { label: 'name', value: 'id' },
      translation: true
    },
    formType: 'select',
  },
  {
    title: '印前团队',
    dataIndex: 'preprint_dept_id',
    width: 10,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: {
      url: '/core/dept/index?role_code=prePrint',
      props: { label: 'name', value: 'id' },
      translation: true
    },
    formType: 'select',
  },
  {
    title: '生产团队',
    dataIndex: 'production_dept_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: {
      url: '/core/dept/index?role_code=production',
      props: { label: 'name', value: 'id' },
      translation: true
    },
    formType: 'select',
  },
  {
    title: '财务团队',
    dataIndex: 'financial_dept_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: {
      url: '/core/dept/index?role_code=financial',
      props: { label: 'name', value: 'id' },
      translation: true
    },
    formType: 'select',
  },
  {
    title: '连锁模式权',
    dataIndex: 'chain_mode',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { name: 'data_status', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'radio',
    // commonRules: [{ required: false, message: '连锁模式权限必填' }],
  },
  {
    title: '小程序相册权',
    dataIndex: 'miniapp_usage',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { name: 'data_status', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'radio',
    // commonRules: [{ required: false, message: '小程序相册权限必填' }],
  },
  {
    title: '下单可用状态',
    dataIndex: 'order_usage',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { name: 'data_status', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'radio',
    // commonRules: [{ required: false, message: '下单状态必填' }],
  },
  {
    title: '账户可用状态',
    dataIndex: 'status',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { name: 'data_status', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'radio',
    // commonRules: [{ required: false, message: '账户状态必填' }],
  },
  // {
  //   title: '备注',
  //   dataIndex: 'remark',
  //   width: 240,
  //   search: true,
  //   addDisplay: true,
  //   editDisplay: true,
  //   hide: false,
  //   formType: 'textarea',
  //   // commonRules: [{ required: false, message: '备注必填' }],
  // },
]);

const crud = reactive({
  api: api.getPageList,
  recycleApi: api.getRecyclePageList,
  showIndex: false,
  searchColNumber: 3,
  pageLayout: 'fixed',
  rowSelection: { showCheckedAll: true },
  operationColumn: true,
  operationColumnWidth: 300,
  add: { show: false, api: api.save, auth: ['/clientApply/save'] },
  edit: { show: true, text: '查看', api: api.update, auth: ['/clientApply/update'] },
  delete: { show: true, api: api.delete, auth: ['/clientApply/destroy'] },
  recovery: { show: true, api: api.recovery, auth: ['/clientApply/recovery'] },
  formOption: { width: 800 },
})

const columns = reactive([
  {
    title: '主键',
    dataIndex: 'id',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: false, message: '主键必填' }],
  },
  {
    title: '人员ID',
    dataIndex: 'sys_user_id',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    // commonRules: [{ required: false, message: '人员ID必填' }],
  },
  {
    title: '系统主账号',
    dataIndex: 'pass_account',
    width: 180,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    readonly: true,
    // rules: [{ required: true, message: '公司名称必填' }],
  },
  {
    title: '公司名称',
    dataIndex: 'company_name',
    width: 180,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    readonly: true,
    // rules: [{ required: true, message: '公司名称必填' }],
  },
  {
    title: '办公地点',
    dataIndex: 'address',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    readonly: true,
    // rules: [{ required: true, message: '办公地点必填' }],
  },
  {
    title: '联系人',
    dataIndex: 'contact',
    width: 180,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    readonly: true,
    // rules: [{ required: true, message: '联系人必填' }],
  },
  {
    title: '手机号',
    dataIndex: 'mobile',
    width: 180,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    readonly: true,
    // rules: [{ required: true, message: '手机号必填' }],
  },
  {
    title: '微信号',
    dataIndex: 'wechat',
    width: 180,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    readonly: true,
    // commonRules: [{ required: true, message: '微信号必填' }],
  },
  {
    title: '品牌名称',
    dataIndex: 'brand_name',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    readonly: true,
    // commonRules: [{ required: true, message: '品牌名称必填' }],
  },
  {
    title: '行业类别',
    dataIndex: 'profession_type_id',
    width: 100,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    dict: { url: '/clientProfessionType/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    formType: 'select',
    readonly: true,
    disabled: true,
    // commonRules: [{ required: false, message: '行业类别必填' }],
  },
  {
    title: '营业执照照片',
    dataIndex: 'business_license',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'upload',
    type: 'image',
    returnType: 'url',
    readonly: true,
    disabled: true,
    // commonRules: [{ required: true, message: '营业执照照片必填' }],
  },
  {
    title: '推荐人手机号',
    dataIndex: 'recommend_mobile',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    readonly: true,
    // commonRules: [{ required: false, message: '推荐人手机号码必填' }],
  },
  {
    title: '审核状态',
    dataIndex: 'status',
    width: 100,
    search: true,
    addDisplay: true, addDefaultValue: 1,
    editDisplay: true,
    hide: false,
    dict: { name: 'bizClientApplyStatus', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'select',
    commonRules: [{ required: false, message: '状态必填' }],
  },
  {
    title: '创建者',
    dataIndex: 'created_by',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: false, message: '创建者必填' }],
  },
  {
    title: '更新者',
    dataIndex: 'updated_by',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: false, message: '更新者必填' }],
  },
  {
    title: '创建时间',
    dataIndex: 'create_time',
    width: 180,
    search: true,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    searchFormType: 'range',
    showTime: true,
    formType: 'date',
    commonRules: [{ required: false, message: '创建时间必填' }],
  },
  {
    title: '修改时间',
    dataIndex: 'update_time',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    searchFormType: 'range',
    showTime: true,
    formType: 'date',
    commonRules: [{ required: false, message: '修改时间必填' }],
  },
])
</script>
