<template>
  <div class="ma-content-block lg:flex justify-between p-4">
    <!-- CRUD 组件 -->
    <ma-crud :options="crud" :columns="columns" ref="crudRef">
    </ma-crud>
  </div>
</template>

<script setup>
  import { ref, reactive, computed } from 'vue'
  import api from '@/api/clientApply'
  import { Message } from '@arco-design/web-vue'

  const crudRef = ref()


  const crud = reactive({
    api: api.getPageList,
    recycleApi: api.getRecyclePageList,
    showIndex: false,
    searchColNumber: 3,
    pageLayout: 'fixed',
    rowSelection: { showCheckedAll: true },
    operationColumn: true,
    operationColumnWidth: 160,
    add: { show: true, api: api.save, auth: ['/clientApply/save'] },
    edit: { show: true, api: api.update, auth: ['/clientApply/update'] },
    delete: { show: true, api: api.delete, auth: ['/clientApply/destroy'] },
    recovery: { show: true, api: api.recovery, auth: ['/clientApply/recovery']},
    formOption: { width: 800 },
  })

  const columns = reactive([
    {
      title: '主键',
      dataIndex: 'id',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '主键必填' }],
    },
    {
      title: '人员ID',
      dataIndex: 'sys_user_id',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '人员ID必填' }],
    },
    {
      title: '品牌权属',
      dataIndex: 'brand_type_id',
      width: 100,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      
      formType: 'select',
      commonRules: [{ required: false, message: '品牌权属必填' }],
    },
    {
      title: '经营类型',
      dataIndex: 'business_type_id',
      width: 100,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      
      formType: 'select',
      commonRules: [{ required: false, message: '经营类型必填' }],
    },
    {
      title: '信用级别',
      dataIndex: 'credit_type_id',
      width: 100,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      
      formType: 'select',
      commonRules: [{ required: false, message: '信用级别必填' }],
    },
    {
      title: '客户级别',
      dataIndex: 'level_type_id',
      width: 100,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      
      formType: 'select',
      commonRules: [{ required: false, message: '客户级别必填' }],
    },
    {
      title: '物流费用方式',
      dataIndex: 'logistics_type_id',
      width: 100,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      
      formType: 'select',
      commonRules: [{ required: false, message: '物流费用方式必填' }],
    },
    {
      title: '行业类别',
      dataIndex: 'profession_type_id',
      width: 100,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      
      formType: 'select',
      commonRules: [{ required: false, message: '行业类别必填' }],
    },
    {
      title: '销售类型',
      dataIndex: 'sales_type_id',
      width: 100,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      
      formType: 'select',
      commonRules: [{ required: false, message: '销售类型必填' }],
    },
    {
      title: '纳税人资格',
      dataIndex: 'taxpayer_type_id',
      width: 100,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      
      formType: 'select',
      commonRules: [{ required: false, message: '纳税人资格必填' }],
    },
    {
      title: '品牌名称',
      dataIndex: 'brand_name',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '品牌名称必填' }],
    },
    {
      title: '品牌证书',
      dataIndex: 'brand_cert_url',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'upload',
      type: 'image',
      returnType: 'url',
      multiple: false,
      commonRules: [{ required: false, message: '品牌证书必填' }],
    },
    {
      title: '营业执照',
      dataIndex: 'business_license_url',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'upload',
      type: 'image',
      returnType: 'url',
      multiple: false,
      commonRules: [{ required: false, message: '营业执照必填' }],
    },
    {
      title: '办公地点',
      dataIndex: 'address',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'textarea',
      commonRules: [{ required: false, message: '办公地点必填' }],
    },
    {
      title: '联系人',
      dataIndex: 'contact',
      width: 180,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '联系人必填' }],
    },
    {
      title: '手机号',
      dataIndex: 'mobile',
      width: 180,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '手机号必填' }],
    },
    {
      title: '微信号',
      dataIndex: 'wechat',
      width: 180,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '微信号必填' }],
    },
    {
      title: '公司名称',
      dataIndex: 'company_name',
      width: 180,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '公司名称必填' }],
    },
    {
      title: '推荐人手机号',
      dataIndex: 'recommend_mobile',
      width: 180,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '推荐人手机号必填' }],
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      search: true,
      addDisplay: true, addDefaultValue: 1,
      editDisplay: true,
      hide: false,
      dict: { name: 'bizClientApplyStatus', props: { label: 'label', value: 'value' }, translation: true },
      formType: 'select',
      commonRules: [{ required: false, message: '状态必填' }],
    },
    {
      title: '创建者',
      dataIndex: 'created_by',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '创建者必填' }],
    },
    {
      title: '更新者',
      dataIndex: 'updated_by',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '更新者必填' }],
    },
    {
      title: '创建时间',
      dataIndex: 'create_time',
      width: 180,
      search: true,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      searchFormType: 'range',
      showTime: true,
      formType: 'date',
      commonRules: [{ required: false, message: '创建时间必填' }],
    },
    {
      title: '修改时间',
      dataIndex: 'update_time',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      searchFormType: 'range',
      showTime: true,
      formType: 'date',
      commonRules: [{ required: false, message: '修改时间必填' }],
    },
  ])
</script>
