<template>
  <div class="justify-between p-4 ma-content-block lg:flex">
    <!-- CRUD 组件 -->
    <ma-crud :options="crud" :columns="columns" ref="crudRef">
    </ma-crud>
  </div>
</template>

<script setup>
  import { ref, reactive, computed } from 'vue'
  import api from '@/api/order'
  import { Message } from '@arco-design/web-vue'

  const crudRef = ref()

  const crud = reactive({
    api: api.getPageList,
    recycleApi: api.getRecyclePageList,
    showIndex: false,
    searchColNumber: 3,
    pageLayout: 'fixed',
    rowSelection: { showCheckedAll: true },
    operationColumn: true,
    operationColumnWidth: 160,
    add: { show: true, api: api.save, auth: ['/order/save'] },
    edit: { show: true, api: api.update, auth: ['/order/update'] },
    delete: { show: true, api: api.delete, auth: ['/order/destroy'] },
    recovery: { show: true, api: api.recovery, auth: ['/order/recovery']},
    formOption: { width: 800 },
  })

  const columns = reactive([
    {
      title: '主键',
      dataIndex: 'id',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: true, message: '主键必填' }],
    },
    {
      title: '订单号',
      dataIndex: 'code',
      width: 180,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '订单号必填' }],
    },
    {
      title: '门店ID',
      dataIndex: 'store_id',
      width: 100,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: true,
      formType: 'select',
      commonRules: [{ required: false, message: '门店ID必填' }],
    },
    {
      title: '门店名',
      dataIndex: 'store_name',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: true, message: '门店名必填' }],
    },
    {
      title: '批次ID',
      dataIndex: 'order_batch_id',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '批次ID必填' }],
    },
    {
      title: '批次号',
      dataIndex: 'order_batch_code',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '批次号必填' }],
    },
    {
      title: '人员ID',
      dataIndex: 'sys_user_id',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '人员ID必填' }],
    },
    {
      title: '收货地址ID',
      dataIndex: 'consignee_id',
      width: 100,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: true,
      formType: 'select',
      commonRules: [{ required: false, message: '收货地址ID必填' }],
    },
    {
      title: '收货地址',
      dataIndex: 'consignee_name',
      width: 180,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: true, message: '收货地址必填' }],
    },
    {
      title: '金额',
      dataIndex: 'amount',
      width: 180,
      search: false,
      addDisplay: true, addDefaultValue: 0.00,
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '金额必填' }],
    },
    {
      title: '卡券金额',
      dataIndex: 'coupon_amount',
      width: 180,
      search: false,
      addDisplay: true, addDefaultValue: 0.00,
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '卡券金额必填' }],
    },
    {
      title: '支付金额',
      dataIndex: 'pay_amount',
      width: 180,
      search: false,
      addDisplay: true, addDefaultValue: 0.00,
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '支付金额必填' }],
    },
    {
      title: '卡券ID',
      dataIndex: 'coupon_id',
      width: 100,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      
      formType: 'select',
      commonRules: [{ required: false, message: '卡券ID必填' }],
    },
    {
      title: '创建者',
      dataIndex: 'created_by',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '创建者必填' }],
    },
    {
      title: '更新者',
      dataIndex: 'updated_by',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '更新者必填' }],
    },
    {
      title: '创建时间',
      dataIndex: 'create_time',
      width: 180,
      search: true,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      searchFormType: 'range',
      showTime: true,
      formType: 'date',
      commonRules: [{ required: false, message: '创建时间必填' }],
    },
    {
      title: '修改时间',
      dataIndex: 'update_time',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      searchFormType: 'range',
      showTime: true,
      formType: 'date',
      commonRules: [{ required: false, message: '修改时间必填' }],
    },
  ])
</script>
