<template>
  <div class="justify-between p-4 ma-content-block lg:flex">
    <!-- CRUD 组件 -->
    <ma-crud :options="crud" :columns="columns" ref="crudRef">
    </ma-crud>
  </div>
</template>

<script setup>
import { ref, reactive, computed } from 'vue'
import api from '@/api/orderErrRecord'
import { Message } from '@arco-design/web-vue'

const crudRef = ref()


const crud = reactive({
  api: api.getPageList,
  recycleApi: api.getRecyclePageList,
  showIndex: false,
  searchColNumber: 3,
  pageLayout: 'fixed',
  rowSelection: { showCheckedAll: true },
  operationColumn: false,
  operationColumnWidth: 160,
  add: { show: false, api: api.save, auth: ['/orderErrRecord/save'] },
  edit: { show: false, api: api.update, auth: ['/orderErrRecord/update'] },
  delete: { show: false, api: api.delete, auth: ['/orderErrRecord/destroy'] },
  recovery: { show: true, api: api.recovery, auth: ['/orderErrRecord/recovery'] },
  formOption: { width: 800 },
})

const columns = reactive([
  {
    title: '主键',
    dataIndex: 'id',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: true, message: '主键必填' }],
  },
  {
    title: '订单号',
    dataIndex: 'order_code',
    width: 200,
    search: true,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    // commonRules: [{ required: true, message: '订单号必填' }],
  },
  {
    title: '变更项',
    dataIndex: 'type',
    width: 180,
    search: false,
    addDisplay: true, addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'select',
    dict: { data: [{ "label": "订单", "value": 'order' }, { "label": "产品", "value": 'goods' }, { "label": "工艺", "value": 'craft' }], translation: true },
  },
  {
    title: '产品',
    dataIndex: 'product_id',
    width: 180,
    search: false,
    addDisplay: true, 
    addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'select',
    dict: { url: '/product/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
  },
  // {
  //   title: '工艺',
  //   dataIndex: 'craft_id',
  //   width: 180,
  //   search: false,
  //   addDisplay: true, 
  //   addDefaultValue: 0.00,
  //   editDisplay: true,
  //   hide: false,
  //   formType: 'select',
  //   dict: { url: '/craft/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
  // },
  {
    title: '字段',
    dataIndex: 'field',
    width: 180,
    search: false,
    addDisplay: true, addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'select',
    dict: { data: [{ "label": "运费", "value": 'freight' }, { "label": "数量", "value": 'nums' }], translation: true },
  },
  {
    title: '原数值',
    dataIndex: 'origin_value',
    width: 180,
    search: false,
    addDisplay: true, addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'input',
    commonRules: [{ required: true, message: '新订单金额必填' }],
  },
  {
    title: '新数值',
    dataIndex: 'new_value',
    width: 180,
    search: false,
    addDisplay: true, addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'input',
    commonRules: [{ required: true, message: '退款金额必填' }],
  },
  {
    title: '备注',
    dataIndex: 'remark',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: true, message: '备注必填' }],
  },
  {
    title: '创建者',
    dataIndex: 'created_by',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: false, message: '创建者必填' }],
  },
  {
    title: '更新者',
    dataIndex: 'updated_by',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: false, message: '更新者必填' }],
  },
  {
    title: '创建时间',
    dataIndex: 'create_time',
    width: 180,
    search: true,
    addDisplay: false,
    editDisplay: false,
    hide: false,
    searchFormType: 'range',
    showTime: true,
    formType: 'date',
    commonRules: [{ required: false, message: '创建时间必填' }],
  },
  {
    title: '修改时间',
    dataIndex: 'update_time',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    searchFormType: 'range',
    showTime: true,
    formType: 'date',
    commonRules: [{ required: false, message: '修改时间必填' }],
  },
])
</script>
