<template>
  <div class="justify-between p-4 ma-content-block lg:flex">
    <!-- CRUD 组件 -->
    <ma-crud :options="crud" :columns="columns" ref="crudRef">
    </ma-crud>
  </div>
</template>

<script setup>
import { ref, reactive, computed } from 'vue'
import api from '@/api/couponItem'
import { Message } from '@arco-design/web-vue'
import { useSysInfoStore } from '@/store'

const visible = ref(false)
const crudRef = ref()
const couponId = ref()
const sysInfoStore = useSysInfoStore()

const open = (row) => {
  couponId.value = row.id
  visible.value = true
  crudRef.value.requestData()
}

const crud = reactive({
  api: api.getPageList,
  beforeRequest: params => {
    params.coupon_id = couponId
  },
  recycleApi: api.getRecyclePageList,
  showIndex: false,
  searchColNumber: 3,
  pageLayout: 'fixed',
  rowSelection: { showCheckedAll: false },
  operationColumn: false,
  operationColumnWidth: 160,
  add: { show: false, api: api.save, auth: ['/couponItem/save'] },
  edit: { show: true, api: api.update, auth: ['/couponItem/update'] },
  delete: { show: true, api: api.delete, auth: ['/couponItem/destroy'] },
  recovery: { show: true, api: api.recovery, auth: ['/couponItem/recovery'] },
  formOption: { width: 800 },
  beforeOpenAdd: () => {
    columns[1].addDefaultValue = Number.parseInt(couponId.value)
    return true
  },
})

const columns = reactive([
  {
    title: '编号',
    dataIndex: 'id',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: true, message: '编号必填' }],
  },
  {
    title: '持有人',
    dataIndex: 'client_id',
    width: 180,
    search: !sysInfoStore.info.is_client,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'select',
    dict: { url: '/clientUser/index?type=all', props: { label: 'name', value: 'client_id' }, translation: true },
    commonRules: [{ required: false, message: '持有人' }],
  },
  {
    title: '名称',
    dataIndex: 'name',
    width: 180,
    search: true,
    addDisplay: false,
    addDefaultValue: '',
    editDisplay: true,
    hide: false,
    formType: 'input',
    commonRules: [{ required: true, message: '名称必填' }],
  },
  {
    title: '卡券ID',
    dataIndex: 'coupon_id',
    width: 100,
    search: false,
    addDisplay: false,
    editDisplay: true,
    hide: true,
    formType: 'select',
    commonRules: [{ required: true, message: '卡券ID必填' }],
  },
  {
    title: '卡券类型',
    dataIndex: 'type',
    width: 100,
    search: false,
    addDisplay: false,
    addDefaultValue: '',
    editDisplay: false,
    hide: true,
    dict: { data: [{ "label": "卡", "value": 1 }, { "label": "券", "value": 2 }], translation: true },
    formType: 'select',
    commonRules: [{ required: false, message: '卡券类型必填' }],
  },
  {
    title: '减免类型',
    dataIndex: 'discount_type',
    width: 100,
    search: true,
    addDisplay: false,
    editDisplay: true,
    hide: false,
    dict: { name: 'bizCouponDiscountType', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'select',
    commonRules: [{ required: true, message: '减免类型必填' }],
  },
  {
    title: '备注',
    dataIndex: 'remark',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'textarea',
    commonRules: [{ required: false, message: '备注必填' }],
  },
  {
    title: '产品',
    dataIndex: 'product_id',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: true,
    hide: false,
    formType: 'select',
    dict: { url: '/product/index?type=all', props: { label: 'name', value: 'id' }, translation: true },
    commonRules: [{ required: true, message: '产品ID必填' }],
  },
  {
    title: '产品类型',
    dataIndex: 'product_type_id',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: false, message: '产品类型必填' }],
  },
  {
    title: '产品级别',
    dataIndex: 'product_grade_id',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: false, message: '产品级别必填' }],
  },
  {
    title: '折扣门槛',
    dataIndex: 'discount_begin',
    width: 180,
    search: false,
    addDisplay: false,
    addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'input',
    commonRules: [{ required: true, message: '折扣门槛必填' }],
  },
  {
    title: '折扣值',
    dataIndex: 'discount_value',
    width: 180,
    search: false,
    addDisplay: false,
    addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'input',
    commonRules: [{ required: true, message: '折扣值必填' }],
  },
  {
    title: '面值',
    dataIndex: 'total',
    width: 180,
    search: false,
    addDisplay: true, addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'input',
    commonRules: [{ required: false, message: '面值必填' }],
  },
  {
    title: '剩余面值',
    dataIndex: 'total_remain',
    width: 180,
    search: false,
    addDisplay: true, addDefaultValue: 0.00,
    editDisplay: true,
    hide: false,
    formType: 'input',
    commonRules: [{ required: true, message: '剩余面值必填' }],
  },
  {
    title: '卡密',
    dataIndex: 'coupon_code',
    width: 220,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    formType: 'input',
    commonRules: [{ required: true, message: '卡密必填' }],
  },
  {
    title: '生效时间',
    dataIndex: 'start_time',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    searchFormType: 'range',
    showTime: true,
    formType: 'date',
    commonRules: [{ required: false, message: '生效时间必填' }],
  },
  {
    title: '失效时间',
    dataIndex: 'end_time',
    width: 180,
    search: false,
    addDisplay: true,
    editDisplay: true,
    hide: false,
    searchFormType: 'range',
    showTime: true,
    formType: 'date',
    commonRules: [{ required: false, message: '失效时间必填' }],
  },
  {
    title: '状态',
    dataIndex: 'status',
    width: 100,
    search: false,
    addDisplay: true, addDefaultValue: 1,
    editDisplay: true,
    hide: false,
    dict: { name: 'data_status', props: { label: 'label', value: 'value' }, translation: true },
    formType: 'radio',
    commonRules: [{ required: false, message: '状态必填' }],
  },
  {
    title: '创建者',
    dataIndex: 'created_by',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: false, message: '创建者必填' }],
  },
  {
    title: '更新者',
    dataIndex: 'updated_by',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    formType: 'input',
    commonRules: [{ required: false, message: '更新者必填' }],
  },
  {
    title: '创建时间',
    dataIndex: 'create_time',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    searchFormType: 'range',
    showTime: true,
    formType: 'date',
    commonRules: [{ required: false, message: '创建时间必填' }],
  },
  {
    title: '修改时间',
    dataIndex: 'update_time',
    width: 180,
    search: false,
    addDisplay: false,
    editDisplay: false,
    hide: true,
    searchFormType: 'range',
    showTime: true,
    formType: 'date',
    commonRules: [{ required: false, message: '修改时间必填' }],
  },
])
</script>
