<template>
  <div class="ma-content-block lg:flex justify-between p-4">
    <!-- CRUD 组件 -->
    <ma-crud :options="crud" :columns="columns" ref="crudRef">
    </ma-crud>
  </div>
</template>

<script setup>
  import { ref, reactive, computed } from 'vue'
  import api from '@/api/orderGoods'
  import { Message } from '@arco-design/web-vue'

  const crudRef = ref()


  const crud = reactive({
    api: api.getPageList,
    recycleApi: api.getRecyclePageList,
    showIndex: false,
    searchColNumber: 3,
    pageLayout: 'fixed',
    rowSelection: { showCheckedAll: true },
    operationColumn: true,
    operationColumnWidth: 160,
    add: { show: true, api: api.save, auth: ['/orderGoods/save'] },
    edit: { show: true, api: api.update, auth: ['/orderGoods/update'] },
    delete: { show: true, api: api.delete, auth: ['/orderGoods/destroy'] },
    recovery: { show: true, api: api.recovery, auth: ['/orderGoods/recovery']},
    formOption: { width: 800 },
  })

  const columns = reactive([
    {
      title: '主键',
      dataIndex: 'id',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: true, message: '主键必填' }],
    },
    {
      title: '订单ID',
      dataIndex: 'order_id',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '订单ID必填' }],
    },
    {
      title: '人员ID',
      dataIndex: 'sys_user_id',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '人员ID必填' }],
    },
    {
      title: '产品ID',
      dataIndex: 'product_id',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '产品ID必填' }],
    },
    {
      title: '产品名称',
      dataIndex: 'product_name',
      width: 180,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: true, message: '产品名称必填' }],
    },
    {
      title: '选项组集合',
      dataIndex: 'craft_group_ids',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '选项组集合必填' }],
    },
    {
      title: '制作选项名称',
      dataIndex: 'craft_name',
      width: 180,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: true, message: '制作选项名称必填' }],
    },
    {
      title: '计价方式',
      dataIndex: 'pricing_type_id',
      width: 180,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: true, message: '计价方式必填' }],
    },
    {
      title: '计价方式名称',
      dataIndex: 'pricing_type_name',
      width: 180,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: true, message: '计价方式名称必填' }],
    },
    {
      title: '计量单位',
      dataIndex: 'pricing_unit_id',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '计量单位必填' }],
    },
    {
      title: '计量单位名称',
      dataIndex: 'pricing_unit_name',
      width: 180,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: true, message: '计量单位名称必填' }],
    },
    {
      title: '宽',
      dataIndex: 'width',
      width: 180,
      search: false,
      addDisplay: true, addDefaultValue: 0.00,
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '宽必填' }],
    },
    {
      title: '高',
      dataIndex: 'height',
      width: 180,
      search: false,
      addDisplay: true, addDefaultValue: 0.00,
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '高必填' }],
    },
    {
      title: '单价',
      dataIndex: 'unit_price',
      width: 180,
      search: false,
      addDisplay: true, addDefaultValue: 0.00,
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '单价必填' }],
    },
    {
      title: '数量',
      dataIndex: 'nums',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '数量必填' }],
    },
    {
      title: '金额',
      dataIndex: 'amount',
      width: 180,
      search: false,
      addDisplay: true, addDefaultValue: 0.00,
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '金额必填' }],
    },
    {
      title: '关联文件名',
      dataIndex: 'associated_file',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'upload',
      type: 'file',
      returnType: 'url',
      multiple: false,
      commonRules: [{ required: false, message: '关联文件名必填' }],
    },
    {
      title: '关联文件路径',
      dataIndex: 'associated_file_url',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'upload',
      type: 'file',
      returnType: 'url',
      multiple: false,
      commonRules: [{ required: false, message: '关联文件路径必填' }],
    },
    {
      title: '修正文件名',
      dataIndex: 'correct_file',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'upload',
      type: 'file',
      returnType: 'url',
      multiple: false,
      commonRules: [{ required: false, message: '修正文件名必填' }],
    },
    {
      title: '修正文件路径',
      dataIndex: 'correct_file_url',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'upload',
      type: 'file',
      returnType: 'url',
      multiple: false,
      commonRules: [{ required: false, message: '修正文件路径必填' }],
    },
    {
      title: '用品名',
      dataIndex: 'gallery_item_name',
      width: 180,
      search: true,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: true, message: '用品名必填' }],
    },
    {
      title: '识别符',
      dataIndex: 'identify',
      width: 180,
      search: false,
      addDisplay: true, 
      editDisplay: true,
      hide: false,
      formType: 'input',
      commonRules: [{ required: false, message: '识别符必填' }],
    },
    {
      title: '备注',
      dataIndex: 'remark',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '备注必填' }],
    },
    {
      title: '创建者',
      dataIndex: 'created_by',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '创建者必填' }],
    },
    {
      title: '更新者',
      dataIndex: 'updated_by',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      formType: 'input',
      commonRules: [{ required: false, message: '更新者必填' }],
    },
    {
      title: '创建时间',
      dataIndex: 'create_time',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      searchFormType: 'range',
      showTime: true,
      formType: 'date',
      commonRules: [{ required: false, message: '创建时间必填' }],
    },
    {
      title: '修改时间',
      dataIndex: 'update_time',
      width: 180,
      search: false,
      addDisplay: false, 
      editDisplay: false,
      hide: true,
      searchFormType: 'range',
      showTime: true,
      formType: 'date',
      commonRules: [{ required: false, message: '修改时间必填' }],
    },
  ])
</script>
